package com.techmarket.util

object TechFormatter {
    private val techMap =
            mapOf(
                    "kotlin" to "Kotlin",
                    "java" to "Java",
                    "python" to "Python",
                    "go" to "Go",
                    "golang" to "Go",
                    "rust" to "Rust",
                    "c++" to "C++",
                    "c#" to "C#",
                    "javascript" to "JavaScript",
                    "typescript" to "TypeScript",
                    "ruby" to "Ruby",
                    "php" to "PHP",
                    "swift" to "Swift",
                    "objective-c" to "Objective-C",
                    "scala" to "Scala",
                    "dart" to "Dart",
                    "elixir" to "Elixir",
                    "clojure" to "Clojure",
                    "haskell" to "Haskell",
                    "lua" to "Lua",
                    "perl" to "Perl",
                    "r" to "R",
                    "shell" to "Shell",
                    "bash" to "Bash",
                    "react" to "React",
                    "angular" to "Angular",
                    "vue" to "Vue.js",
                    "nextjs" to "Next.js",
                    "next.js" to "Next.js",
                    "svelte" to "Svelte",
                    "ember" to "Ember.js",
                    "backbone" to "Backbone.js",
                    "html" to "HTML",
                    "css" to "CSS",
                    "sass" to "Sass",
                    "less" to "Less",
                    "tailwind" to "Tailwind CSS",
                    "bootstrap" to "Bootstrap",
                    "material-ui" to "Material UI",
                    "redux" to "Redux",
                    "graphql" to "GraphQL",
                    "spring" to "Spring",
                    "spring boot" to "Spring Boot",
                    "django" to "Django",
                    "flask" to "Flask",
                    "fastapi" to "FastAPI",
                    "node" to "Node.js",
                    "nodejs" to "Node.js",
                    "node.js" to "Node.js",
                    "express" to "Express",
                    "nest" to "NestJS",
                    "nestjs" to "NestJS",
                    "ruby on rails" to "Ruby on Rails",
                    "laravel" to "Laravel",
                    "asp.net" to "ASP.NET",
                    "dotnet" to ".NET",
                    ".net" to ".NET",
                    "android" to "Android",
                    "ios" to "iOS",
                    "flutter" to "Flutter",
                    "react native" to "React Native",
                    "xamarin" to "Xamarin",
                    "ionic" to "Ionic",
                    "kotlin multiplatform" to "Kotlin Multiplatform",
                    "aws" to "AWS",
                    "gcp" to "GCP",
                    "azure" to "Azure",
                    "docker" to "Docker",
                    "kubernetes" to "Kubernetes",
                    "k8s" to "Kubernetes",
                    "terraform" to "Terraform",
                    "ansible" to "Ansible",
                    "chef" to "Chef",
                    "puppet" to "Puppet",
                    "jenkins" to "Jenkins",
                    "github actions" to "GitHub Actions",
                    "gitlab ci" to "GitLab CI",
                    "circleci" to "CircleCI",
                    "travis ci" to "Travis CI",
                    "linux" to "Linux",
                    "ubuntu" to "Ubuntu",
                    "serverless" to "Serverless",
                    "lambda" to "AWS Lambda",
                    "cloudformation" to "CloudFormation",
                    "sql" to "SQL",
                    "postgresql" to "PostgreSQL",
                    "postgres" to "PostgreSQL",
                    "mysql" to "MySQL",
                    "mongodb" to "MongoDB",
                    "mongo" to "MongoDB",
                    "redis" to "Redis",
                    "elasticsearch" to "Elasticsearch",
                    "cassandra" to "Cassandra",
                    "dynamodb" to "DynamoDB",
                    "mariadb" to "MariaDB",
                    "oracle" to "Oracle",
                    "sql server" to "SQL Server",
                    "sqlite" to "SQLite",
                    "couchbase" to "Couchbase",
                    "neo4j" to "Neo4j",
                    "bigquery" to "BigQuery",
                    "snowflake" to "Snowflake",
                    "redshift" to "Redshift",
                    "hadoop" to "Hadoop",
                    "spark" to "Apache Spark",
                    "kafka" to "Apache Kafka",
                    "rabbitmq" to "RabbitMQ",
                    "activemq" to "ActiveMQ",
                    "airflow" to "Apache Airflow",
                    "dbt" to "dbt",
                    "databricks" to "Databricks",
                    "pandas" to "Pandas",
                    "numpy" to "NumPy",
                    "scikit-learn" to "scikit-learn",
                    "tensorflow" to "TensorFlow",
                    "pytorch" to "PyTorch"
            )

    fun format(tech: String): String {
        return techMap[tech.lowercase()] ?: tech.replaceFirstChar { it.uppercase() }
    }

    fun getAllOfficialNames(): Set<String> {
        return techMap.values.toSet()
    }
}
